services:
  productclienthubapi:
    image: productclienthubapi
    build:
      context: .
      dockerfile: ProductClientHubAPI/Dockerfile
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "ProductClientHub"
    port:
      - "5432:5432"
